server:
  port: 9000
spring:
  application:
    name: AudioConverterBot
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/test
    password: karpunets
    username: karpunets
    hikari:
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.apache: INFO
    com.zaxxer.hikari: INFO
    com.karpunets: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log

telegram:
  bot:
    username: AudioConverterBot
    token: 560931351:AAFxvrTrpbAg6Ro3CdmiWb3OhZkWOOojO5Q
ffmpeg:
  ffmpeg-path: ./ffmpeg-4.0-win64-shared/bin/ffmpeg
  ffprobe-path: ./ffmpeg-4.0-win64-shared/bin/ffprobe
storage:
  audio:
    src: ./tmp